### ISSUE TITLE
Remove unnecessary texts from Session ('end command' and 'OK') 

### ISSUE THREAD

**Issue by jakeolins** [jakeolins/indetail2.0#12]
Resolve two bugs related to passing of superfluous messages:

1. Both Learners and Experts are getting an auto-reply of "OK" to any message they send to the the Broker 
2. The endCommand is being passed to the Learner after the Learner receives the learnerSignoff

 Expected behavior for bug 1:
 - Only messages initiated by learner, expert or broker via a dynamic value are passed from the fromPerson to the toPerson

 Expected behavior for bug 2:
 - Expert sends the endCommand
 - Learner receives the learnerSignoff message
 - Learner does NOT receive the endCommand

**Comment by cucucachu** [comment]
This should now be fixed due to changes in issue #3
